### ISSUE TITLE
Companion Selection Choices Changing After Patching Selection Blueprint

### ISSUE THREAD

**Issue by BurlyWurly** [OwlcatOpenSource/WrathModificationTemplate#17]
So I'm finding a weird interaction where companions default features that stem from a selection blueprint are getting changed when that selection blueprint is patched. Saved games where the companion has already been recruited are unaffected, but for example:

```
{
"m_Features": [
    "!bp_621e1bb8e1d5e114da5a107351f5c7b3",
    "!bp_5214a43c0169c654b9ca456e296cdd7c",
    "!bp_9da9faf5f0ef4904db4a59a22dafbb06
  ],
  "m_AllFeatures": [
    "!bp_621e1bb8e1d5e114da5a107351f5c7b3",
    "!bp_5214a43c0169c654b9ca456e296cdd7c",
    "!bp_9da9faf5f0ef4904db4a59a22dafbb06
  ]
}
```

This patches the BackgroundsStreetUrchinSelection and removes the original Mugger option and replaces it with a modified one. Pickpocket and Acrobat are untouched. However, both companions with the Pickpocket background (Seelah and Woljiff) are now being recruited as Acrobats. I would have thought I'd need to patch/recreate the companion's FeatureList to have an effect on that. Anyone have any insight on this one?

**Comment by ijuintekka** [comment]
I've been unable to replicate your problem, both with your blueprint and a blueprint I've corrected. Seelah is given the pickpocket background in both cases.

In any case, you are missing closing quotes on both references to the pickpocket blueprint, which is breaking your patch.

**Comment by BurlyWurly** [comment]
That appears to have somehow gotten dropped in copying over to github for some reason, they're there in my patch file.

I imagine it takes more of the mod to cause the issue, so it's not just the mere act of patching the selection choice. It doesn't make any sense, because all the companions' feature lists contain an explicit blueprint reference to their original background, not a one of which is getting touched in any way.

**Comment by Mrquincy** [comment]
Hi - 

I’ve read you guys back and forth on a few threads and believe you can help me. Since you two are clearly super smart.

I finished the game and would like to edit dialog. I didn’t like for example : (evil choice) - “I don’t like you, die! “

Is there a place that holds all of this text that allows for easy modification? I want to rewrite the whole script.

thanks!

**Comment by BurlyWurly** [comment]
That's nothing I've even come close to messing with. I am *guessing* there are blueprints that direct all the dialogue and options using strings, and if you identify the strings you're looking for you can then patch them in the localization to whatever you want. I couldn't begin to tell you where to look though, you'd have to really dig through the blueprint dumps.

**Comment by ijuintekka** [comment]
If it's just editing dialogue and not adding new lines and choices, it's as simple as editing Wrath_Data/StreamingAssets/Localization/enGb.json (Or your own language json).

Otherwise adding new lines and choices requires editing the blueprints for conversations, which isn't too hard compared to any other blueprint, just a matter of finding the right one. I created a patch to modify the dialogue in Sosiel's final companion quest to give me a new choice because I did some events out of sequence and screwed myself out of the good ending. So it's definitely doable.
